[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
solc-version = "0.8.25"
optimizer = true
optimizer-runs = 10_000_000


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
